name: absen_desa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  encrypt: ^5.0.3
  excel: ^4.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geolocator: ^12.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  supabase_flutter: ^2.5.11
  syncfusion_flutter_xlsio: ^26.2.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
